# Auto-label rules for PRs

# --- Backend & DB ---
backend:
  - changed-files:
      - any-glob-to-any-file: [ "src/**", "pom.xml", "Dockerfile", "docker-compose.yml" ]

db:
  - changed-files:
      - any-glob-to-any-file: [ "src/main/resources/db/**" ]

liquibase:
  - changed-files:
      - any-glob-to-any-file: [ "src/main/resources/db/**" ]

auth:
  - changed-files:
      - any-glob-to-any-file: [ "src/main/java/**/auth/**", "src/**/security/**" ]

graphql:
  - changed-files:
      - any-glob-to-any-file: [ "src/main/graphql/**", "src/**/*.graphql" ]

# --- Frontend ---
frontend:
  - changed-files:
      - any-glob-to-any-file: [ "frontend/**", "frontend/**/*", "frontend/Dockerfile" ]

angular:
  - changed-files:
      - any-glob-to-any-file: [ "frontend/**", "frontend/**/*", "frontend/Dockerfile" ]

test:
  - changed-files:
      - any-glob-to-any-file: [ "src/test/**", "src/**/*Test.java", "frontend/**/*.spec.ts", "frontend/e2e/**" ]

# --- Infra & CI/CD ---
ci/cd:
  - changed-files:
      - any-glob-to-any-file: [ ".github/workflows/**", ".github/labeler.yml" ]

github-actions:
  - changed-files:
      - any-glob-to-any-file: [ ".github/workflows/**", ".github/labeler.yml" ]

infra:
  - changed-files:
      - any-glob-to-any-file: [ ".github/workflows/**", ".github/labeler.yml", "gitHub-actions/**" ]

docker:
  - changed-files:
      - any-glob-to-any-file: [ "docker-compose.yml", "Dockerfile" ]

deployment:
  - changed-files:
      - any-glob-to-any-file: [ "vercel.json", "railway.json" ]

vercel:
  - changed-files:
      - any-glob-to-any-file: [ "vercel.json" ]

railway:
  - changed-files:
      - any-glob-to-any-file: [ "railway.json", "**/railway.json" ]

# --- Docs & Misc ---
documentation:
  - changed-files:
      - any-glob-to-any-file: [ "docs/**", "README.md" ]

foundation:
  - changed-files:
      - any-glob-to-any-file: [ "foundation/**" ]

enhancement:
  - changed-files:
      - any-glob-to-any-file: [ "src/**/feature/**", "frontend/**" ]
