package com.youssef.GridPulse.domain.message.payload;

/**
 * Represents the decoded payload structure of a BMS (Battery Management System) message.
 * <p>
 * A BMS message is generated by the BMS module and includes data from both the battery hardware
 * and the Battery Prediction model. The original message is transmitted as a Base64-encoded JSON
 * string, which, when decoded, yields this structured payload.
 * </p>
 *
 * <p><strong>Fields:</strong></p>
 * <ul>
 *   <li><strong>batteryId</strong> – Unique identifier of the battery unit.</li>
 *   <li><strong>batteryVolt</strong> – Current voltage of the battery, measured in volts (V).</li>
 *   <li><strong>batterySoc</strong> – State of Charge (SoC) of the battery, expressed as a percentage (%).</li>
 *   <li><strong>batteryCycle</strong> – Total number of charge/discharge cycles the battery has undergone.</li>
 *   <li><strong>batterySoh</strong> – State of Health (SoH) of the battery, expressed as a percentage (%).</li>
 *   <li><strong>batteryTemperature</strong> – Current temperature of the battery, measured in degrees Celsius (°C).</li>
 * </ul>
 *
 * <p>Additional metadata such as message type (always {@code 4}) and timestamp are handled at the envelope level
 * and are not part of this decoded payload structure.</p>
 *
 * <p>This payload supports battery diagnostics, predictive maintenance, and energy system optimization.</p>
 */
public record BmsPayload(
        int batteryId,
        float batteryVolt,
        float batterySoc,
        int batteryCycle,
        float batterySoh,
        float batteryTemperature
) {}
