package com.youssef.GridPulse.domain.message.payload;

/**
 * Represents the payload structure for an Inverter message.
 * <p>
 * This message is generated by the Inverter module and provides real-time performance metrics
 * related to the inverter's electrical output and thermal state.
 * </p>
 *
 * <p><strong>Fields:</strong></p>
 * <ul>
 *   <li><strong>out_pwr</strong> – Current output power of the inverter, measured in watts (W).</li>
 *   <li><strong>voltage</strong> – Output voltage, measured in volts (V).</li>
 *   <li><strong>current</strong> – Output current, measured in amperes (A).</li>
 *   <li><strong>frequency</strong> – Output frequency, measured in hertz (Hz).</li>
 *   <li><strong>efficiency</strong> – Current efficiency of the inverter, expressed as a percentage (%).</li>
 *   <li><strong>temperature</strong> – Current temperature of the inverter, measured in degrees Celsius (°C).</li>
 * </ul>
 *
 * <p>This payload supports performance monitoring, thermal diagnostics, and energy system optimization.</p>
 */
public record InverterPayload(
        float out_pwr,
        float voltage,
        float current,
        float frequency,
        float efficiency,
        float temperature
) {}

