package com.youssef.GridPulse.domain.message.payload;

/**
 * Represents the payload structure for a meter message.
 * <p>
 * This message is generated by the Meter module and conveys real-time power metrics
 * related to the device's energy consumption and production.
 * </p>
 *
 * <p><strong>Fields:</strong></p>
 * <ul>
 *   <li><strong>pwrIn</strong> – Current power consumption in watts (W).</li>
 *   <li><strong>pwrOut</strong> – Current power production in watts (W).</li>
 * </ul>
 *
 * <p>This payload supports energy flow monitoring, diagnostics, and real-time analytics dashboards.</p>
 */
public record MeterPayload(
        float pwrIn,
        float pwrOut
) {}

