package com.youssef.GridPulse.domain.message.payload;

/**
 * Represents the payload structure for a System message.
 * <p>
 * This message is generated by the system module and provides a snapshot of the device's
 * current health and resource usage. It includes CPU, memory, and disk utilization,
 * as well as GPS location and system temperature.
 * </p>
 *
 * <p><strong>Fields:</strong></p>
 * <ul>
 *   <li><strong>cpuUsage</strong> – Current CPU usage in percentage (%).</li>
 *   <li><strong>memoryUsage</strong> – Current memory usage in percentage (%).</li>
 *   <li><strong>diskUsage</strong> – Current disk usage in percentage (%).</li>
 *   <li><strong>temperature</strong> – Current system temperature in Celsius.</li>
 *   <li><strong>latitude</strong> – GPS latitude coordinate of the device.</li>
 *   <li><strong>longitude</strong> – GPS longitude coordinate of the device.</li>
 * </ul>
 *
 * <p>This payload supports system diagnostics, telemetry dashboards, and health monitoring workflows.
 * Severity classification is handled separately at the message level.</p>
 */
public record SystemPayload(
        int cpuUsage,       // percentage
        int memoryUsage,    // percentage
        int diskUsage,      // percentage
        int temperature,    // in Celsius
        double latitude,    // GPS latitude
        double longitude    // GPS longitude
) {}


