export enum DeviceStatus {
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE',
  MAINTENANCE = 'MAINTENANCE',
  ERROR = 'ERROR',
  NEW = 'NEW',
  UNKNOWN = 'UNKNOWN',
  COMMISSIONING = 'COMMISSIONING',
  STANDBY = 'STANDBY',
  DECOMMISSIONED = 'DECOMMISSIONED',
  RETIRED = 'RETIRED',
}
